### ISSUE TITLE
Send HTTP requests from inside the workers (fetch support)

### ISSUE THREAD

**Issue by Angelmmiguel** [vmware-labs/wasm-workers-server#165]
### Is your feature request related to a problem? Please describe.

When I write a worker, I can only rely on the data that comes from a local file (mounted folders), environments variables or hardcoded in code. This reduces the kind of projects I can develop.

### Describe the solution you'd like

I would like to call an external HTTP API from inside a worker. Every language has its own way to do it, so I want to use those common patterns. For example, the `fetch` method is the most common API for calling an HTTP endpoint in JavaScript.

To follow the capability-based approach, I want to configure the HTTP endpoints a worker can call. I want to avoid a worker calling random HTTP endpoints. For this, I would add a new section in the TOML file called "features". This object includes one configuration per feature like: 

```toml
[features]
[features.fetch]
allowed_domains = ["https://example.com"]
force_ssl = true
```

### Host implementation

- [x] Define the bindings with WIT (#168)
- [x] Implement the bindings on the host side (#168)
- [x] Configure the workers so developers configure the allowed requests. By default, all requests will be rejected. (#174)

### Language implementation

I will start with JavaScript, but I will extend the support to other languages soon:

- [x] JavaScript (#169)
- [x] Rust (#171)
- [x] Go (#173)

#### Future implementations

- Python (#176)
- Ruby (#177)

**Comment by Angelmmiguel** [comment]
Now that we have support for Go, Rust and JavaScript, I plan to split the remaining languages (Python and Ruby) into separate tasks. Note that languages that requires an external runtime follows a different lifecycle and we can publish them afterwards.

With the new versions, Python and Ruby workers will continue working but they won't be able to make HTTP requests yet. We will work on adding support to those soon 😄
